### ISSUE TITLE
[Bug] The button "Mon compte" in client/index is redirecting borne/index 

### ISSUE THREAD

**Issue by BaptTF** [CETEN-OpenBar/bar#106]
**Décriver l'incident** \
[Bug] The button "Mon compte" in client/index is redirecting borne/index 

**Etapes pour reproduire l'erreur** \
Etapes:
Se connecter sur client/commande
Aller sur son profil
cliquer sur Mon compte

**Comportement attendu**\
Rediriger sur client/index

**Screenshots**\
![image](https://github.com/user-attachments/assets/511e8150-a948-4aa9-8744-18be6539594c)

**Informations complémentaires**
 - OS: NixOS
 - Browser Firefox

**Comment by Ciflire** [comment]
je me pencherai ptet dessus demain en vrai
