### ISSUE TITLE
Feature Request - Gestion des comptes via panel admin

### ISSUE THREAD

**Issue by GoldmanEquinox** [CETEN-OpenBar/bar#14]
Pouvoir re-link un compte avec une autre carte (historique des puces NFC passées sur le lecteur)

**Comment by GoldmanEquinox** [comment]
Pouvoir reset le PIN d'un utilisateur via panel Admin

**Comment by yyewolf** [comment]
> Pouvoir reset le PIN d'un utilisateur via panel Admin Edit : envoi d'un mail pour reset ?

Problème d'envoyer un mail c'est qu'un compte google est pas forcément link a un compte, on peut reset a 0000 dans ce cas ?

**Comment by GoldmanEquinox** [comment]
Okay pour 0000 tant que la personne peut changer via son compte après

**Comment by BaptTF** [comment]
> Pouvoir re-link un compte avec une autre carte (historique des puces NFC passées sur le lecteur)

On peut dans admin/accounts ajouter une nouvelle carte NFC linker à un compte
