### ISSUE TITLE
[URGENT] Feature request - Système d'authentification pour le Bureau du Bar

### ISSUE THREAD

**Issue by TydraoXalys** [CETEN-OpenBar/bar#56]
## Situation actuelle
Pour s'authentifier sur le PC comptoir, les membres du bar ont besoin de scanner leur carte et de renseigner le même code PIN que celui utilisé pour faire des commandes. Cependant, la sécurité de ce système d'authentification n'est pas suffisante pour le PC comptoir. En effet,
1. Une personne qui n'est pas membre du bar peut très aisément récupérer le code pin d'un membre du bureau (et le pavé numérique physique que vous voulez mettre _**ne résoudra pas**_ ce problème). Il suffit alors que ce membre du bureau oublie sa carte (ce qui arrive souvent) et tout le monde peut potentiellement avoir accès au local.
2. Dès lors que l'UI du PC comptoir est active (suite à la connexion d'un membre du bar), n'importe qui peut effectuer ces opérations critiques avec son propre code pin (on a testé).

## Solution au problème
1. Vérifier les permissions associées à l'utilisateur au scan de la carte sur le lecteur NFC du PC comptoir.
2. Implémenter un système d'authentification par mot de passe spécifique aux membres du bar, implémenté sur le PC comptoir (on verra si c'est nécessaire pour le PC admin) et qui est demandé pour effectuer les opérations critiques (connexion au PC comptoir, ouverture de la porte, ouverture de la caisse, etc...). La création et la modification du mot de passe doit se faire sur le PC admin. La suppression peut se faire soit sur le PC admin manuellement, soit automatiquement lorsqu'on retire les droits de "membre du bureau" à la personne.

**Comment by yyewolf** [comment]
`1. Vérifier les permissions associées à l'utilisateur au scan de la carte sur le lecteur NFC du PC comptoir.` est déjà implémenté.

Le second le sera

**Comment by yyewolf** [comment]
Fixed : https://github.com/CETEN-OpenBar/bar/releases/tag/v0.0.28.1
