### ISSUE TITLE
Bug Issue - Produits sans historique de vente dans la trésorerie

### ISSUE THREAD

**Issue by adrien-lrsse** [CETEN-OpenBar/bar#57]
Dans Tréso/Historique,
Quand je cherche certains produits, il ne se passe rien alors qu'il y a bien eu des ventes (entre le 01/10/2023 et le 31/10/2023)
exemples :
- 3ds Bacon
- Don rose X.X€

**Comment by yyewolf** [comment]
Les achats de produits de PayMyBar n'ont pas pu être exportés malheureusement, on peut toujours le faire a la main pour les dernières infos manquantes sur l'ancienne base
