### ISSUE TITLE
[URGENT] Bug Issue - Catégories de prix

### ISSUE THREAD

**Issue by adrien-lrsse** [CETEN-OpenBar/bar#59]
Pour le bar il doit exister 6 catégories de prix dont voici le détail
- Le "Prix Coûtant" : c'est le prix des "membres du bureau" (qu'on on fait une réappro c'est ce prix qui est modifié)
- Le "Prix Bar" : c'est pour les "staff bar"
- Le "Prix Privilégié" : c'est pour les "membres priviliégiés"
- Le "Prix Menu : c'est le prix des produits quand ils font parties d'un menu.
- Le "Prix CETEN" : c'est pour les "membres CETEN"
- Le "Prix Externe" : c'est pour les "membres"

Il ne doit exister que ces catégories de prix. 
Le naming des prix est celui donné entre guillement

**Comment by yyewolf** [comment]
https://github.com/CETEN-OpenBar/bar/tree/price-rename

Besoins de tests encore, j'ai les procedures de migrations de prêtes en plus.
