### ISSUE TITLE
[Bug issue] Validation des rechargements

### ISSUE THREAD

**Issue by TydraoXalys** [CETEN-OpenBar/bar#60]
Lorsqu'on fait un rechargement sur le PC comptoir, après avoir rempli les différents champs, si on appuie sur la touche Entrée (parce qu'on a des vieux réflexes) puis qu'on appuie sur Valider, une erreur s'affiche et oblige à F5.

A priori, les rechargements sont pas pris en compte (car non affichés dans l'historique) mais à vérifier.

**Comment by Ciflire** [comment]
On peut désormais valider un rechargement avec la commande entrer
Je laisse l'issue ouverte, il faut fix le fait de ne pas ajouter des input avec des keypress supplémentaire une fois que la carte a été badgée

**Comment by yyewolf** [comment]
https://github.com/CETEN-OpenBar/bar/commit/55548c28bce19849a276468ea7df3181e88e5406
