### ISSUE TITLE
[Feature] Retour des photos de profil (et des surnoms aussi)

### ISSUE THREAD

**Issue by Dolhen-James** [CETEN-OpenBar/bar#64]
Aurelien et Edgar, ils veulent le retour des photos de profil et des surnoms (dissociés du mail .net).
Et en vrai, plein d'autres le veulent aussi.

**Comment by yyewolf** [comment]
Les photos de profil existent, il suffit de changer son icone google,
Les nicknames arrivent : https://github.com/CETEN-OpenBar/bar/commit/34a230afd0b9f2ad63bd270839d9f2b26b1ebe03
